export const analyticsConfig = {
  tables: [
    {name: 'asset_2', label: 'Asset'},
    {name: 'contravention', label: 'Contravention'},
    {name: 'job', label: 'Job'},
    {name: 'rmq_sale', label: 'RMQ Sale'},
    {name: 'project_employee', label: 'EmployeeVSProject'},
    {name: 'cashier_ticket_2', label: 'Cashier Ticket'}
  ],
  exposedParams: {
    asset_2: [
      'status',
      'project_id',
      'type_asset',
      'model_id',
      'zone_id',
      'configurations',
      'asset_notes',
      'ip_address',
      'vehicle_plate',
      'vehicle_plate_ar',
      'vehicle_brand',
      'vehicle_country',
      'vehicle_country_ar',
      'status_vehicle',
    ],
    contravention: [
      'plate_country',
      'plate_country_ar',
      'plate_type',
      'violation',
      'violation_ar',
      'violation_code',
      'amount',
      'project_name',
      'zone_name',
      'status',
      'status_review',
      'status_challenge',
      'sent_by',
      'car_plate',
      'car_plate_ar',
      'car_type',
      'car_type_ar',
      'car_brand',
      'car_model',
      'car_color',
      'car_color_ar',
      'intersection_name_en',
      'street_name_en',
      'street_name_ar'
    ],
    job: [
      'job_type',
      'plate_country',
      'plate_type',
      'plate_type_ar',
      'project_name',
      'violation',
      'amount',
      'zone_name',
      'status',
      'car_plate',
      'car_plate_ar',
      'car_brand',
      'car_model',
      'car_color',
      'car_color_ar',
      'taker_username',
      'geolocation_towing',
      'vehicle_codification',
      'intersection_name_en',
      'intersection_name_ar',
      'street_name_en',
      'street_name_ar',
      'sent_by'
    ],
    rmq_sale: [
      'pndtype',
      'pndcode',
      'parkcode',
      'parkdesc',
      'currency',
      'server_date',
      'products_tarif',
      'products_place',
      'products_currency',
      'products_origin',
      'products_custom',
      'payments_details',
      'status',
      'cell_level',
    ],
    project_employee: [
      'project_id',
      'employee_id',
      'supervisor_id',
    ],
    cashier_ticket_2: [
      'ticket_number',
      'paid_mode',
      'unpaid_reason',
      'card_transaction',
      'detail_services',
      'detail_tariffs',
      'remark',
      'action',
      'category',
      'reference',
      'detail_promo',
    ],
  },
  numericParams: {
    asset_2: ['*'],
    contravention: ['amount', 'observation_time'],
    job: ['amount', 'latitude_towing_delivered', 'longitude_towing_delivered', 'latitude_towing_pickup', 'longitude_towing_pickup'],
    rmq_sale: ['spend_duration', 'products_amount', 'products_paidduration', 'products_user', 'products_freeduration'],
    project_employee: ['*'],
    cashier_ticket_2: ['amount_due', 'amount_validated', 'amount_promo', 'amount_vat', 'amount_total'],
  },
  dateParams: {
    asset_2: ['eol_at', 'deployed_at', 'created_at', 'warranty_until'],
    contravention: ['creation', 'sent_at', 'evolved_into_cn_at', 'canceled_at'],
    job: ['creation', 'date_end', 'date_start', 'sent_at'],
    rmq_sale: ['sale_date', 'products_startdate', 'products_enddate', 'created_at'],
    project_employee: ['start_date', 'end_date'],
    cashier_ticket_2: ['paid_at', 'issued_at'],
  },
  mapParams: {
    asset_2: ['latitude', 'longitude'],
    contravention: ['latitude', 'longitude'],
    job: ['latitude', 'longitude'],
    rmq_sale: [],
    project_employee: [],
    cashier_ticket_2: [],
  },
  periods: ['day', 'week', 'month', 'year'],
  chartTypes: ['bar', 'pie', 'line', 'map'],
  mapTypes: ['OpenStreetMap', 'Esri', 'CartoDB'],
  aggregations: ['COUNT', 'SUM', 'AVG', 'MIN', 'MAX'],
  timeAggregations: ['day', 'week', 'month', 'year'],
  baseChartOptions: {
    pie: {
      responsive: true,
      legend: {
        position: 'right',
      }
    },
    line: {
      responsive: true,
      legend: {
        position: 'right',
      }
    },
    bar: {
      responsive: true,
      legend: {
        position: 'right',
      }
    }
  }
};
