export const Currencies = [
  {code : 'SA', currencyCode : 'SAR', currencyName : 'Saudi Riyal'},
  {code : 'AE', currencyCode : 'AED', currencyName : 'United Arab Emirates Dirham'},
  {code : 'BH', currencyCode : 'BHD', currencyName : 'Bahraini Dinar'},
  {code : 'KW', currencyCode : 'KWD', currencyName : 'Kuwaiti Dinar'},
  {code : 'QA', currencyCode : 'QAR', currencyName : 'Qatari Rial'},
  {code : 'OM', currencyCode : 'OMR', currencyName : 'Omani Rial'},
  {code : 'US', currencyCode : 'USD', currencyName : 'United States Dollar'},
  {code : 'EU', currencyCode : 'EUR', currencyName : 'Euro'},
  {code : 'AF', currencyCode : 'AFN', currencyName : 'Afghan Afghani'},
  {code : 'AL', currencyCode : 'ALL', currencyName : 'Albanian Lek'},
  {code : 'AM', currencyCode : 'AMD', currencyName : 'Armenian Dram'},
  {code : 'NL', currencyCode : 'ANG', currencyName : 'Netherlands Antillean Guilder'},
  {code : 'AO', currencyCode : 'AOA', currencyName : 'Angolan Kwanza'},
  {code : 'AR', currencyCode : 'ARS', currencyName : 'Argentine Peso'},
  {code : 'AU', currencyCode : 'AUD', currencyName : 'Australian Dollar'},
  {code : 'AW', currencyCode : 'AWG', currencyName : 'Aruban Florin'},
  {code : 'AZ', currencyCode : 'AZN', currencyName : 'Azerbaijani Manat'},
  {code : 'BA', currencyCode : 'BAM', currencyName : 'Bosnia-Herzegovina Convertible Mark'},
  {code : 'BB', currencyCode : 'BBD', currencyName : 'Barbadian Dollar'},
  {code : 'BD', currencyCode : 'BDT', currencyName : 'Bangladeshi Taka'},
  {code : 'BG', currencyCode : 'BGN', currencyName : 'Bulgarian Lev'},
  {code : 'BI', currencyCode : 'BIF', currencyName : 'Burundian Franc'},
  {code : 'BM', currencyCode : 'BMD', currencyName : 'Bermudan Dollar'},
  {code : 'BN', currencyCode : 'BND', currencyName : 'Brunei Dollar'},
  {code : 'BO', currencyCode : 'BOB', currencyName : 'Bolivian Boliviano'},
  {code : 'BR', currencyCode : 'BRL', currencyName : 'Brazilian Real'},
  {code : 'BS', currencyCode : 'BSD', currencyName : 'Bahamian Dollar'},
  {code : 'BT', currencyCode : 'BTN', currencyName : 'Bhutanese Ngultrum'},
  {code : 'BW', currencyCode : 'BWP', currencyName : 'Botswanan Pula'},
  {code : 'BY', currencyCode : 'BYN', currencyName : 'Belarusian Ruble'},
  {code : 'BZ', currencyCode : 'BZD', currencyName : 'Belize Dollar'},
  {code : 'CA', currencyCode : 'CAD', currencyName : 'Canadian Dollar'},
  {code : 'CD', currencyCode : 'CDF', currencyName : 'Congolese Franc'},
  {code : 'CH', currencyCode : 'CHF', currencyName : 'Swiss Franc'},
  {code : 'CL', currencyCode : 'CLF', currencyName : 'Chilean Unit of Account (UF)'},
  {code : 'CL', currencyCode : 'CLP', currencyName : 'Chilean Peso'},
  {code : 'CN', currencyCode : 'CNH', currencyName : 'Chinese Yuan (Offshore)'},
  {code : 'CN', currencyCode : 'CNY', currencyName : 'Chinese Yuan'},
  {code : 'CO', currencyCode : 'COP', currencyName : 'Colombian Peso'},
  {code : 'CR', currencyCode : 'CRC', currencyName : 'Costa Rican Colón'},
  {code : 'CU', currencyCode : 'CUC', currencyName : 'Cuban Convertible Peso'},
  {code : 'CU', currencyCode : 'CUP', currencyName : 'Cuban Peso'},
  {code : 'CV', currencyCode : 'CVE', currencyName : 'Cape Verdean Escudo'},
  {code : 'CZ', currencyCode : 'CZK', currencyName : 'Czech Republic Koruna'},
  {code : 'DJ', currencyCode : 'DJF', currencyName : 'Djiboutian Franc'},
  {code : 'DK', currencyCode : 'DKK', currencyName : 'Danish Krone'},
  {code : 'DO', currencyCode : 'DOP', currencyName : 'Dominican Peso'},
  {code : 'DZ', currencyCode : 'DZD', currencyName : 'Algerian Dinar'},
  {code : 'EG', currencyCode : 'EGP', currencyName : 'Egyptian Pound'},
  {code : 'ER', currencyCode : 'ERN', currencyName : 'Eritrean Nakfa'},
  {code : 'ET', currencyCode : 'ETB', currencyName : 'Ethiopian Birr'},
  {code : 'FJ', currencyCode : 'FJD', currencyName : 'Fijian Dollar'},
  {code : 'FK', currencyCode : 'FKP', currencyName : 'Falkland Islands Pound'},
  {code : 'GB', currencyCode : 'GBP', currencyName : 'British Pound Sterling'},
  {code : 'GE', currencyCode : 'GEL', currencyName : 'Georgian Lari'},
  {code : 'GG', currencyCode : 'GGP', currencyName : 'Guernsey Pound'},
  {code : 'GH', currencyCode : 'GHS', currencyName : 'Ghanaian Cedi'},
  {code : 'GI', currencyCode : 'GIP', currencyName : 'Gibraltar Pound'},
  {code : 'GM', currencyCode : 'GMD', currencyName : 'Gambian Dalasi'},
  {code : 'GN', currencyCode : 'GNF', currencyName : 'Guinean Franc'},
  {code : 'GT', currencyCode : 'GTQ', currencyName : 'Guatemalan Quetzal'},
  {code : 'GY', currencyCode : 'GYD', currencyName : 'Guyanaese Dollar'},
  {code : 'HK', currencyCode : 'HKD', currencyName : 'Hong Kong Dollar'},
  {code : 'HN', currencyCode : 'HNL', currencyName : 'Honduran Lempira'},
  {code : 'HR', currencyCode : 'HRK', currencyName : 'Croatian Kuna'},
  {code : 'HT', currencyCode : 'HTG', currencyName : 'Haitian Gourde'},
  {code : 'HU', currencyCode : 'HUF', currencyName : 'Hungarian Forint'},
  {code : 'ID', currencyCode : 'IDR', currencyName : 'Indonesian Rupiah'},
  {code : 'IL', currencyCode : 'ILS', currencyName : 'Israeli New Sheqel'},
  {code : 'IM', currencyCode : 'IMP', currencyName : 'Manx pound'},
  {code : 'IN', currencyCode : 'INR', currencyName : 'Indian Rupee'},
  {code : 'IQ', currencyCode : 'IQD', currencyName : 'Iraqi Dinar'},
  {code : 'IR', currencyCode : 'IRR', currencyName : 'Iranian Rial'},
  {code : 'IS', currencyCode : 'ISK', currencyName : 'Icelandic Króna'},
  {code : 'JE', currencyCode : 'JEP', currencyName : 'Jersey Pound'},
  {code : 'JM', currencyCode : 'JMD', currencyName : 'Jamaican Dollar'},
  {code : 'JO', currencyCode : 'JOD', currencyName : 'Jordanian Dinar'},
  {code : 'JP', currencyCode : 'JPY', currencyName : 'Japanese Yen'},
  {code : 'KE', currencyCode : 'KES', currencyName : 'Kenyan Shilling'},
  {code : 'KG', currencyCode : 'KGS', currencyName : 'Kyrgystani Som'},
  {code : 'KH', currencyCode : 'KHR', currencyName : 'Cambodian Riel'},
  {code : 'KM', currencyCode : 'KMF', currencyName : 'Comorian Franc'},
  {code : 'KP', currencyCode : 'KPW', currencyName : 'North Korean Won'},
  {code : 'KR', currencyCode : 'KRW', currencyName : 'South Korean Won'},
  {code : 'KY', currencyCode : 'KYD', currencyName : 'Cayman Islands Dollar'},
  {code : 'KZ', currencyCode : 'KZT', currencyName : 'Kazakhstani Tenge'},
  {code : 'LA', currencyCode : 'LAK', currencyName : 'Laotian Kip'},
  {code : 'LB', currencyCode : 'LBP', currencyName : 'Lebanese Pound'},
  {code : 'LK', currencyCode : 'LKR', currencyName : 'Sri Lankan Rupee'},
  {code : 'LR', currencyCode : 'LRD', currencyName : 'Liberian Dollar'},
  {code : 'LS', currencyCode : 'LSL', currencyName : 'Lesotho Loti'},
  {code : 'LY', currencyCode : 'LYD', currencyName : 'Libyan Dinar'},
  {code : 'MA', currencyCode : 'MAD', currencyName : 'Moroccan Dirham'},
  {code : 'MD', currencyCode : 'MDL', currencyName : 'Moldovan Leu'},
  {code : 'MG', currencyCode : 'MGA', currencyName : 'Malagasy Ariary'},
  {code : 'MK', currencyCode : 'MKD', currencyName : 'Macedonian Denar'},
  {code : 'MM', currencyCode : 'MMK', currencyName : 'Myanma Kyat'},
  {code : 'MN', currencyCode : 'MNT', currencyName : 'Mongolian Tugrik'},
  {code : 'MO', currencyCode : 'MOP', currencyName : 'Macanese Pataca'},
  {code : 'MR', currencyCode : 'MRO', currencyName : 'Mauritanian Ouguiya (pre-2018)'},
  {code : 'MR', currencyCode : 'MRU', currencyName : 'Mauritanian Ouguiya'},
  {code : 'MU', currencyCode : 'MUR', currencyName : 'Mauritian Rupee'},
  {code : 'MV', currencyCode : 'MVR', currencyName : 'Maldivian Rufiyaa'},
  {code : 'MW', currencyCode : 'MWK', currencyName : 'Malawian Kwacha'},
  {code : 'MX', currencyCode : 'MXN', currencyName : 'Mexican Peso'},
  {code : 'MY', currencyCode : 'MYR', currencyName : 'Malaysian Ringgit'},
  {code : 'MZ', currencyCode : 'MZN', currencyName : 'Mozambican Metical'},
  {code : 'NA', currencyCode : 'NAD', currencyName : 'Namibian Dollar'},
  {code : 'NG', currencyCode : 'NGN', currencyName : 'Nigerian Naira'},
  {code : 'NI', currencyCode : 'NIO', currencyName : 'Nicaraguan Córdoba'},
  {code : 'NO', currencyCode : 'NOK', currencyName : 'Norwegian Krone'},
  {code : 'NP', currencyCode : 'NPR', currencyName : 'Nepalese Rupee'},
  {code : 'NZ', currencyCode : 'NZD', currencyName : 'New Zealand Dollar'},
  {code : 'PA', currencyCode : 'PAB', currencyName : 'Panamanian Balboa'},
  {code : 'PE', currencyCode : 'PEN', currencyName : 'Peruvian Nuevo Sol'},
  {code : 'PG', currencyCode : 'PGK', currencyName : 'Papua New Guinean Kina'},
  {code : 'PH', currencyCode : 'PHP', currencyName : 'Philippine Peso'},
  {code : 'PK', currencyCode : 'PKR', currencyName : 'Pakistani Rupee'},
  {code : 'PL', currencyCode : 'PLN', currencyName : 'Polish Zloty'},
  {code : 'PY', currencyCode : 'PYG', currencyName : 'Paraguayan Guarani'},
  {code : 'RO', currencyCode : 'RON', currencyName : 'Romanian Leu'},
  {code : 'RS', currencyCode : 'RSD', currencyName : 'Serbian Dinar'},
  {code : 'RU', currencyCode : 'RUB', currencyName : 'Russian Ruble'},
  {code : 'RW', currencyCode : 'RWF', currencyName : 'Rwandan Franc'},
  {code : 'SB', currencyCode : 'SBD', currencyName : 'Solomon Islands Dollar'},
  {code : 'SC', currencyCode : 'SCR', currencyName : 'Seychellois Rupee'},
  {code : 'SD', currencyCode : 'SDG', currencyName : 'Sudanese Pound'},
  {code : 'SE', currencyCode : 'SEK', currencyName : 'Swedish Krona'},
  {code : 'SG', currencyCode : 'SGD', currencyName : 'Singapore Dollar'},
  {code : 'SH', currencyCode : 'SHP', currencyName : 'Saint Helena Pound'},
  {code : 'SL', currencyCode : 'SLL', currencyName : 'Sierra Leonean Leone'},
  {code : 'SO', currencyCode : 'SOS', currencyName : 'Somali Shilling'},
  {code : 'SR', currencyCode : 'SRD', currencyName : 'SuricurrencyNamese Dollar'},
  {code : 'SS', currencyCode : 'SSP', currencyName : 'South Sudanese Pound'},
  {code : 'ST', currencyCode : 'STD', currencyName : 'São Tomé and Príncipe Dobra (pre-2018)'},
  {code : 'ST', currencyCode : 'STN', currencyName : 'São Tomé and Príncipe Dobra'},
  {code : 'SV', currencyCode : 'SVC', currencyName : 'Salvadoran Colón'},
  {code : 'SY', currencyCode : 'SYP', currencyName : 'Syrian Pound'},
  {code : 'SZ', currencyCode : 'SZL', currencyName : 'Swazi Lilangeni'},
  {code : 'TH', currencyCode : 'THB', currencyName : 'Thai Baht'},
  {code : 'TJ', currencyCode : 'TJS', currencyName : 'Tajikistani Somoni'},
  {code : 'TM', currencyCode : 'TMT', currencyName : 'Turkmenistani Manat'},
  {code : 'TN', currencyCode : 'TND', currencyName : 'Tunisian Dinar'},
  {code : 'TO', currencyCode : 'TOP', currencyName : 'Tongan Pa\'anga'},
  {code : 'TR', currencyCode : 'TRY', currencyName : 'Turkish Lira'},
  {code : 'TT', currencyCode : 'TTD', currencyName : 'Trinidad and Tobago Dollar'},
  {code : 'TW', currencyCode : 'TWD', currencyName : 'New Taiwan Dollar'},
  {code : 'TZ', currencyCode : 'TZS', currencyName : 'Tanzanian Shilling'},
  {code : 'UA', currencyCode : 'UAH', currencyName : 'Ukrainian Hryvnia'},
  {code : 'UG', currencyCode : 'UGX', currencyName : 'Ugandan Shilling'},
  {code : 'UY', currencyCode : 'UYU', currencyName : 'Uruguayan Peso'},
  {code : 'UZ', currencyCode : 'UZS', currencyName : 'Uzbekistan Som'},
  {code : 'VE', currencyCode : 'VEF', currencyName : 'Venezuelan Bolívar Fuerte (Old)'},
  {code : 'VE', currencyCode : 'VES', currencyName : 'Venezuelan Bolívar Soberano'},
  {code : 'VN', currencyCode : 'VND', currencyName : 'VietcurrencyNamese Dong'},
  {code : 'VU', currencyCode : 'VUV', currencyName : 'Vanuatu Vatu'},
  {code : 'WS', currencyCode : 'WST', currencyName : 'Samoan Tala'},
  {code : 'YE', currencyCode : 'YER', currencyName : 'Yemeni Rial'},
  {code : 'ZA', currencyCode : 'ZAR', currencyName : 'South African Rand'},
  {code : 'ZM', currencyCode : 'ZMW', currencyName : 'Zambian Kwacha'},
  {code : 'ZW', currencyCode : 'ZWL', currencyName : 'Zimbabwean Dollar'}
];
